/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "GUIComponents/CustomLookAndFeel.h"

class FilterGuiAudioProcessorEditor  : public AudioProcessorEditor,
                                            public ComboBox::Listener
{
public:

    FilterGuiAudioProcessorEditor (FilterGuiAudioProcessor&);
    ~FilterGuiAudioProcessorEditor();
    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged) override;

private:
    class ParameterSlider;
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    FilterGuiAudioProcessor& processor;
    ScopedPointer<ParameterSlider> frequencyCutoff, gainSlider, filtOrderSlider;

    //GUI Components
    CustomLookAndFeel customLookAndFeel;

    Label gainLabel, frequencyCutoffLabel, filterLabel, filterOrderLabel;
    
    ComboBox filterTypeDropDown;

    
    FilterGuiAudioProcessor& getProcessor() const
    {
        return static_cast<FilterGuiAudioProcessor&> (processor);
    }
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FilterGuiAudioProcessorEditor)
};

#endif  // PLUGINEDITOR_H_INCLUDED
